name: Release Build

on:
  workflow_dispatch:
  push:
      tags:
        - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.get-tag.outputs.tag-name }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag name
        id: get-tag
        run: echo "tag-name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Prepare build files
        run: |
          # 解码base64编码的keystore文件
          echo "${{ secrets.KEY_BASE64 }}" | base64 -d > app/app.key
          
          # 写入签名配置到local.properties
          echo "${{ secrets.SIGNING_CONFIG }}" > local.properties
          
          # 写入Google Services配置
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Gradle Build
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: artifacts
          path: app/build/outputs/apk/release/*.apk

  create-release:
    needs: build
    runs-on: ubuntu-latest
    name: Release app
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: ./apk

      - name: Rename APKs
        run: |
          cd ./apk
          mv app-arm64-v8a-release.apk     RikkaHub-${{ needs.build.outputs.tag-name }}-arm64-v8a.apk
          mv app-x86_64-release.apk        RikkaHub-${{ needs.build.outputs.tag-name }}-x86_64.apk
          mv app-universal-release.apk     RikkaHub-${{ needs.build.outputs.tag-name }}-universal.apk

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ needs.build.outputs.tag-name }} \
            ./apk/RikkaHub-${{ needs.build.outputs.tag-name }}-arm64-v8a.apk \
            ./apk/RikkaHub-${{ needs.build.outputs.tag-name }}-x86_64.apk \
            ./apk/RikkaHub-${{ needs.build.outputs.tag-name }}-universal.apk \
            --repo ${{ github.repository }} \
            --title "${{ needs.build.outputs.tag-name }}" \
            --generate-notes
